import keyboard
import time
time.sleep(2)
keyboard.write("58")
keyboard.press_and_release("tab")
keyboard.write("Female")
keyboard.press_and_release("tab")
keyboard.write("0")
keyboard.press_and_release("tab")
keyboard.write("100")
keyboard.press_and_release("tab")
keyboard.write("0")
keyboard.press_and_release("tab")
keyboard.write("122")
keyboard.press_and_release("tab")
keyboard.write("No")
keyboard.press_and_release("tab")
keyboard.write("1")
keyboard.press_and_release("tab")
keyboard.write("1")
keyboard.press_and_release("tab")
keyboard.write("0")
keyboard.press_and_release("tab")
keyboard.write("Fixed Defect")
