import keyboard
import time
time.sleep(2)
keyboard.write("52")
keyboard.press_and_release("tab")
keyboard.write("Female")
keyboard.press_and_release("tab")
keyboard.write("0")
keyboard.press_and_release("tab")
keyboard.write("125")
keyboard.press_and_release("tab")
keyboard.write("1")
keyboard.press_and_release("tab")
keyboard.write("168")
keyboard.press_and_release("tab")
keyboard.write("No")
keyboard.press_and_release("tab")
keyboard.write("1")
keyboard.press_and_release("tab")
keyboard.write("2")
keyboard.press_and_release("tab")
keyboard.write("2")
keyboard.press_and_release("tab")
keyboard.write("Reversable")
